SET SERVEROUTPUT ON;

DECLARE 

    TYPE CURSOR_VARIABLE IS REF CURSOR;
    V1 CURSOR_VARIABLE;
    
    TYPE C2 IS REF CURSOR RETURN DEPARTMENTS%ROWTYPE;
    V2 C2;
    
     EMPLEADOS EMPLOYEES%ROWTYPE;
     DEPARTAMENTO DEPARTMENTS%ROWTYPE;
     PAISES COUNTRIES%ROWTYPE;
     
BEGIN

    OPEN V1 FOR SELECT * FROM employees;
    FETCH V1 INTO EMPLEADOS;
    DBMS_OUTPUT.PUT_LINE('ELEMENTOS DE LA TABLA EMPLEADOS');
    DBMS_OUTPUT.put_line(EMPLEADOS.EMPLOYEE_ID);
    DBMS_OUTPUT.put_line(EMPLEADOS.FIRST_NAME);
    DBMS_OUTPUT.put_line(EMPLEADOS.LAST_NAME);
    
    CLOSE V1;
    DBMS_OUTPUT.PUT_LINE('');
    
    OPEN V2 FOR SELECT * FROM DEPARTMENTS;
     FETCH V2 INTO DEPARTAMENTO;
    WHILE V2%FOUND LOOP
    
    DBMS_OUTPUT.PUT_LINE(DEPARTAMENTO.DEPARTMENT_ID);
    FETCH V2 INTO DEPARTAMENTO;
    END LOOP;
    
    CLOSE V2;
     DBMS_OUTPUT.PUT_LINE('');
     
    OPEN V1 FOR SELECT * FROM COUNTRIES;
    FETCH V1 INTO PAISES ;
    DBMS_OUTPUT.PUT_LINE('PAISES');
    DBMS_OUTPUT.PUT_LINE(PAISES.COUNTRY_ID);
    DBMS_OUTPUT.PUT_LINE(PAISES.COUNTRY_NAME);
    DBMS_OUTPUT.PUT_LINE(PAISES.REGION_ID);
    
    CLOSE V1;
    
    OPEN V1 FOR SELECT * FROM COUNTRIES;
    FETCH V1 INTO PAISES;
    DBMS_OUTPUT.PUT_LINE(PAISES.COUNTRY_NAME);
    WHILE V1%FOUND LOOP
    DBMS_OUTPUT.PUT_LINE(PAISES.COUNTRY_NAME);
    FETCH V1 INTO PAISES;
    END LOOP;
    CLOSE V1;
END;
/

